### ISSUE TITLE
Sporadic failure on shouldAcceptAbortOnScheduledPoll.

### ISSUE THREAD

**Issue by dpwspoon** [reaktivity/nukleus-http-cache.java#72]
![image](https://user-images.githubusercontent.com/2014623/35198353-75024f22-fea2-11e7-9dcd-7df01e616995.png)

**Comment by dpwspoon** [comment]
Does not reproduce locally for me

**Comment by dpwspoon** [comment]
http2 nukleus (the only usecase for the cache) never will exercise this condition as of now

**Comment by jfallows** [comment]
No longer reproduces.

Note: `k3po` and `k3po-nukleus-ext` have since been improved.
